### ISSUE TITLE
[FEATURE] Add ability to specify nodePort

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan-reference#107]
In my current usecase I want to add a service of type `NodePort`. Currently this is possible but without the ability to specify the `nodePort` itself.
So if I create a service of type `NodePort` I get a service with a (by kubernetes) randomly added `NodePort` between `30000-32767`

Official docs:
https://kubernetes.io/docs/concepts/services-networking/service/#nodeport

Expected input:
```yaml
  components:
    myapp:
[...]
      ports:
        my-service:
          service_port: 80
          container_port: 80
          node_port: 30007
```

expected outcome:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
```

The old libsonnet generator has it:
https://github.com/kapicorp/kapitan-reference/blob/92b13dca8ce3ae6cdd118251efe0c649ee3d46bf/lib/kap.libsonnet#L132

The new kadet generator doesn't honor the `node_port`

I tried to add `port.node_port` here but get only supports two arguments:
https://github.com/kapicorp/kapitan-reference/blob/cfe6f51992be47e154425692fa19b41b50a4a0f9/components/generators/kubernetes/__init__.py#L636

So I exceeded my knowledge and time to solve this issue myself :-1:
