### ISSUE TITLE
Create services on a per-port basis

### ISSUE THREAD

**Issue by alanhughes** [kapicorp/kapitan-reference#32]
Really glad I stumbled upon this - the manifest generators are super handy and make defining multiple homogenous services really easy 👍 

When using the deployment/service manifest generator, if the `service` directive is specified then a service is created for each port defined in the container. I have a use-case in which we have a container that runs two ports, a user-facing http port and an admin port for healthchecks/metrics, and it is only necessary to create a service for the former. It's not a big deal, but more for neatness/not creating unnecessary services.

I guess a simple (?) fix would be to only create services for which service_port is defined. So, for the following configuration, only the `http-server` port would have a service created.
```
parameters:
  applications:
    <app-name>:
      component_defaults:
        service:
          type: ClusterIP
        ports:
          admin-server:
            container_port: <port-1>
          http-server:
            container_port: <port-2>
            service_port: 80
```
