### ISSUE TITLE
Liveness + Readiness Probe HealthCheck config

### ISSUE THREAD

**Issue by alanhughes** [kapicorp/kapitan-reference#34]
It'd be brilliant if we could specify different configurations for the liveness and readiness probes separately. In the current framework, any configuration applied to one healthcheck is applied to both, but I think it's a reasonable requirement to have different configurations, e.g. a separate http path for readiness and liveness.

My vision for this is that `readiness` and `liveness` become fields directly under `healthcheck`, with the configuration defined beneath them, rather than have them as members of an array, so

```yaml
      healthcheck:
        readiness:
          type: http
          port: http
          path: /_health
          timeout_seconds: 3
```
for example

Have had a go at hacking around locally but it's a bit unclear where to change given all the different places where project structure is defined - schema.json, service_component, schemas.libsonnet, kap.libsonnet...any pointers? :)
