### ISSUE TITLE
[Generators][Ingress] Allow to generate different types/allow to specify hostnames

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan-reference#58]
**Types of Ingress**
[k8s-docs for Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/)
- Ingress backed by a single Service
- Simple fanout
- Name based virtual hosting
- TLS
- Load balancing

**Ingress host/hostname**
Currently the Ingress hostname is set to a wildcard.
In order to change this, please allow the generator to pick up a host.
```yaml
parameters:
  ingresses:
    sonarqube-ingress:
      host: "foo.bar.com"
        paths:
          - path: /
[...]
      host: "*.foo.com"
        paths:
          - path: /
[...]
```
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
  - host: "foo.bar.com"
    http:
      paths:
      - pathType: Prefix
        path: "/bar"
        backend:
          service:
            name: service1
            port:
              number: 80
  - host: "*.foo.com"
    http:
      paths:
      - pathType: Prefix
        path: "/foo"
        backend:
          service:
            name: service2
            port:
              number: 80
```
