### ISSUE TITLE
[Enhancement] Please improve generator for Job/CronJob

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan-reference#67]
# Usecase:
I'd like to add a component which is a CronJob. The Cronjob should run a container with a volume mount.
The backup (cronjob) should then be written to the PVC.
After that my k8s backup mechanism get track of the rest.

# Affected Resources
1. CronJob Resource
2. PV Resources
3. PVC Resources

# Whats does not work as expected?
The libsonnet simply uses `podspec` which contains replicas and strategy by default
Next the `restartPolicy` can only be one of "OnFailure", "Never".
Additionally `strategy` isnt supported
Also the generated `MatchLabels` doesn't fit onto a CronJob resource.

```yaml
    #
    # Backup
    #
    postgres_backup:
      type: deployment
      image: ${postgres:image}
      replicas: ""
      schedule: ${postgres:backup:interval}
      env:
        PGHOST: ${database:host}
        PGPORT: ${database:port}
        PGDATABASE: ${database:name}
        PGUSER: ${database:user}
        PGPASSWORD: ${postgres:users:postgres:password}
      volume_mounts:
        pg-backup:
          mountPath: /backup/${database:name}
          subPath: pgdata
      args: 
        -  DUMP_FILE_NAME="backupOn`date +%Y-%m-%d-%H-%M`.dump"
        -  echo "Creating dump: $DUMP_FILE_NAME"
        -  cd pg_backup
        -  pg_dump -C -w --format=c --blobs > $DUMP_FILE_NAME
        -  if [ $? -ne 0 ]; then
        -    rm $DUMP_FILE_NAME
        -    echo "Back up not created, check db connection settings"
        -  exit 1
        -  fi
        -  echo 'Successfully Backed Up'
        -  exit 0
```
# The error
```bash
$ kubectl apply --recursive -f compiled/gitea/manifests/
The CronJob "postgres_backup" is invalid: 
* spec.jobTemplate.spec.template.spec.restartPolicy: Required value: valid values: "OnFailure", "Never"
* spec.jobTemplate.spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/managed-by":"kapitan", "app.kubernetes.io/part-of":"gitea", "name":"postgres_backup"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: `selector` will be auto-generated

```
