### ISSUE TITLE
Allow to generate a hash value for a component

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan-reference#70]
As discussed [in Slack](https://kubernetes.slack.com/archives/C981W2HD3/p1613485190319500)

> Hey, I'm searching for a mechanism where my deployment will be triggered after running kubectl apply -f compiled/xyz/manifests.
With the default kubernetes scheduler this is (AFAIK) just possible when something else in the spec.template section has changed. I previously used ansible/jinja2 to hash all files and then put it as a label into the deployment.
Does someone has an idea how to achive this with kapitan?

I'd like to have a function which provides a label per component e.g. Postgres.
This label then should be automatically added to every resource referring to this Postgres instance. 

For example
```yaml
$ cat deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

```yaml
$ cat configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true    
```

```bash
$ cat deployment.yml configmap.yml | sha256sum
d8dd3fa5923f8c52908b63532599bae4333155cfbb0c2f26114fdbd6663ab024  -
```
After changing the containerPort from 80 to 8080
```bash
cat deployment.yml configmap.yml | sha256sum
9ea6395c10946fc80d61a00b5c4770654b9f44ec56dd1dac2bd9e9a4dc16a27f  -
```

**Comment by ademariag** [comment]
Hi @Moep90 I am not sure I understand. 

If you change containerPort from 80 to 8080 Kubernetes will automatically detect it. why would you need a hash for that?

Is the main use-case to detect when a secret or a configmap has changed?

If so, my approach would be to have "versioned secrets/configs"

for instance:


```
components:
  nginx:
    image: nginx
    config_maps:
      config:
        data:
          file: content1 
```

would generate a ConfigMap: nginx-abc123

if the config map changes, the sha would change:

```
components:
  nginx:
    image: nginx
    config_maps:
      config:
        data:
          file: content2
```
would generate a ConfigMap: nginx-abd321

The deployment would then also change accordingly, and kubernetes would roll-update it.
