### ISSUE TITLE
Allow to generate to add different service types

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan-reference#71]
Slack discussion here: https://kubernetes.slack.com/archives/C981W2HD3/p1613723263349100
Official kubernetes Documentation:
https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types

There are several proposals I see how this can work:
## Option 1:
```yaml
      service:
        clusterip-serviceName:
          type: ClusterIP
          ports:
            udp-video1:
              service_port: ${jvb:udp_media}
              container_port: ${jvb:udp_media}
              protocol: UDP
        loadbalancer-serviceName:
          type: Loadbalancer
          ports:
            udp-video2:
              service_port: ${jvb:udp_media}
              container_port: ${jvb:udp_media}
              protocol: UDP
        nodeport-serviceName:
          type: NodePort
          ports:
            udp-video3:
              service_port: ${jvb:udp_media}
              container_port: ${jvb:udp_media}
              protocol: UDP
        externalname-serviceName:
          type: ExternalName
          ports:
            udp-video4:
              service_port: ${jvb:udp_media}
              container_port: ${jvb:udp_media}
              protocol: UDP
```
## Option 2:
```yaml
     service:
     ports:
        udp-video:
          type: ClusterIP
          service_port: ${jvb:udp_media}
          container_port: ${jvb:udp_media}
          protocol: UDP
        udp-other:
          type: Loadbalancer
          service_port: ${jvb:udp_media}
          container_port: ${jvb:udp_media}
          protocol: UDP
        udp-video2:
          type: ExternalName
          service_port: ${jvb:udp_media}
          container_port: ${jvb:udp_media}
          protocol: UDP
        udp-other2:
          type: NodePort
          service_port: ${jvb:udp_media}
          container_port: ${jvb:udp_media}
          protocol: UDP
```
## Option 3:
```yaml
      service:
        clusterip:
          - udp-video:
            service_port: ${jvb:udp_media}
            container_port: ${jvb:udp_media}
            protocol: UDP
        loadbalancer:
          - udp-other:
            service_port: ${jvb:udp_media}
            container_port: ${jvb:udp_media}
            protocol: TCP
          - udp-video2:
            service_port: ${jvb:udp_media}
            container_port: ${jvb:udp_media}
            protocol: UDP
          - udp-other2:
            service_port: ${jvb:udp_media}
            container_port: ${jvb:udp_media}
            protocol: TCP
        nodeport:
          - udp-other3:
            service_port: ${jvb:udp_media}
            container_port: ${jvb:udp_media}
            protocol: UDP
        externalname:
          - udp-other4:
            service_port: ${jvb:udp_media}
            container_port: ${jvb:udp_media}
            protocol: UDP
```

**Comment by Moep90** [comment]
# values.yml

```yaml
server:
  ha:
    enabled: true
    raft:
      enabled: true
```
# helming
```shell
helm repo add hashicorp https://helm.releases.hashicorp.com
helm template vault hashicorp/vault --values values.yml --namespace my-vault-namespace > vault.rendered.yml
```
