### ISSUE TITLE
Allow generators to generate  PodSecurityPolicy

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan-reference#72]
Official kubernetes Documentation:
https://kubernetes.io/docs/concepts/policy/pod-security-policy/

There are several proposals I see how this can work:

```yaml
parameters:
  #
  # Parameters
  #
  sensu-backend:
    image: sensu/sensu:6
    version: 6
    component: go
    # gRPC sensu-storage-client
    grpc-storage-client: 2379
    # grpc storage peer
    grpc-storage-peer: 2380
    # sensu-web-ui
    web-ui: 3000
    # profiling
    profiling: 6060
    # api
    api: 8080
    # websocket
    agent-api: 8081

  # Componment/s
  components:
    sensu-backend:
      type: statefulset
      image: ${sensu-backend:image}
      imagePullPolicy: Always
      [...]

      podsecuritypolicy:
        privileged: true
        allowPrivilegeEscalation: true
        allowedCapabilities:
        - '*'
        volumes:
        - '*'
        hostNetwork: true
        hostPorts:
        - min: 0
        max: 65535
        hostIPC: true
        hostPID: true
        runAsUser:
          rule: 'RunAsAny'
        seLinux:
          rule: 'RunAsAny'
        supplementalGroups:
          rule: 'RunAsAny'
        fsGroup:
          rule: 'RunAsAny'
```

Will generate:
```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
  annotations:
    manifests.kapicorp.com/generated: 'true'
  labels:
    app.kubernetes.io/component: go
    app.kubernetes.io/managed-by: kapitan
    app.kubernetes.io/part-of: sensu
    app.kubernetes.io/version: 6
spec:
  privileged: false
  # Required to prevent escalations to root.
  allowPrivilegeEscalation: false
  # This is redundant with non-root + disallow privilege escalation,
  # but we can provide it for defense in depth.
  requiredDropCapabilities:
    - ALL
  # Allow core volume types.
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    # Assume that persistentVolumes set up by the cluster admin are safe to use.
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
```
