### ISSUE TITLE
Allow generators to pick up value references not just by environment variables

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan-reference#75]
hey,
for several projects especially Statefulsets we need to reference values into another container like described here:
https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/

Also we would like to use them as labels to for example attach the current node-name as pod label.

This can in Kapitan look like this:
```yaml
parameters:
  components:
    app-name:
       # Metadata
      pod:
        labels:
          "app.kubernetes.io/running-on":
            fieldRef:
              fieldPath: spec.nodeName

      labels:
        app.kubernetes.io/version: ${sensu-backend:version}
        app.kubernetes.io/component: ${sensu-backend:component}
      
      env:
        MYSQL_ROOT_PASSWORD:
          secretKeyRef:
            key: mysql-root-password
        POD_NAME:
          fieldRef:
            fieldPath: metadata.name

```
