### ISSUE TITLE
Allow generators to generate initContainers

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan-reference#77]
Please add support for the `initContainers`.

https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

```yaml
parameters:
  sensu-backend:
    image: sensu/sensu:6
    version: '6'
    component: go
  components:
    sensu-backend:
      replicas: 3
      type: statefulset
      image: ${sensu-backend:image}
      imagePullPolicy: Always

      # Possible solution
      initContainers:
        nginxA:
          image: yzv
          command: [
            "bash", "-c",
            "|", "set -ex"
          ]
        nginxB:
          image: yzv
          command: [
            "bash", "-c",
            "|", "set -ex"
          ]
```
