### ISSUE TITLE
Allow usage of automountServiceAccountToken

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan-reference#93]
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

Allow usage of:
```yaml
apiVersion: apps/v1
kind: Deployment/Statefulset
metadata:
  name: "my-release-harbor-portal"
  labels:
    heritage: Helm
    release: my-release
    chart: harbor
    app: "harbor"
    component: portal
spec:
  template:
    spec:
automountServiceAccountToken
```

Discoverd adopting helm-portal
