### ISSUE TITLE
Allow usage of startupProbe

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan-reference#94]
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

discoverd in harbor-core:
```yaml
apiVersion: apps/v1
kind: Deployment/Statefulset
metadata:
  name: my-release-harbor-core
  labels:
    heritage: Helm
    release: my-release
    chart: harbor
    app: "harbor"
    component: core
spec:
  template:
    spec:
      containers:
      - name: core
[...]
        startupProbe:
          httpGet:
            path: /api/v2.0/ping
            scheme: HTTP
            port: 8080
          failureThreshold: 360
          initialDelaySeconds: 10
          periodSeconds: 10
[...]
```
