### ISSUE TITLE
Allow usage of podManagementPolicy

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan-reference#95]
Pod Management Policies 
In Kubernetes 1.7 and later, StatefulSet allows you to relax its ordering guarantees while preserving its uniqueness and identity guarantees via its .spec.podManagementPolicy field.

https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: my-vault-namespace
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
spec:
  serviceName: vault-internal
  podManagementPolicy: Parallel
```
