### ISSUE TITLE
Allow usage of container-lifecycle-hooks

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan-reference#96]
https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/

```yaml
          lifecycle:
            # Vault container doesn't receive SIGTERM from Kubernetes
            # and after the grace period ends, Kube sends SIGKILL.  This
            # causes issues with graceful shutdowns such as deregistering itself
            # from Consul (zombie services).
            preStop:
              exec:
                command: [
                  "/bin/sh", "-c",
                  # Adding a sleep here to give the pod eviction a
                  # chance to propagate, so requests will not be made
                  # to this pod while it's terminating
                  "sleep 5 && kill -SIGTERM $(pidof vault)",
                ]
```

**Comment by Moep90** [comment]
lifecycle is already there. simply overlooked it 

```yaml
parameters:
  components:
    vault:
      lifecycle:
        preStop:
          exec:
            command:
            - /bin/sh
            - -c
            - sleep 5 && kill -SIGTERM $(pidof vault)
```
